azopenaiGPT4Vision:
  resource_name: ""
  endpoint: ""
  token: ""
  apiversion: ""
azopenaiGPT4o:
  resource_name: ""
  endpoint: ""
  token: ""
  apiversion: ""
gcpvertex:
  model_name: ""
  keypath: ""
  project: ""
  location: ""
anthropic:
  name: ""
  model_name: ""
  token: ""